---
title: "Dirichlet parameter estimation 2"
author: "Daniel T. Fuller"
date: '2023-03-23'
output:
  html_document: default
  pdf_document: default
bibliography: references.bib
fontsize: 12pt
---

```{r setup, include=FALSE, echo=FALSE}
library(dplyr)
library(magrittr)
library(ggplot2)

library(sirt)

knitr::opts_chunk$set(echo = TRUE)
set.seed(0473961)
```

```{r functions}
smean <- function(data){  #Return the averages of columns
  means <- data %>%
    apply(2, mean)
  return(means)
}

svar <- function(data){ #Return the sample variances of columns
  vars <- data %>%
    apply(2, var)
  return(vars)  
}

MME <- function(data){ #Compute the MME for Dirichlet parameters 
  means <- smean(data)
  vars <- svar(data)
  estimates <- c()
  for(j in 1:length(data[1,])){
    jth_estimate <- means[j]*((means[j]*(1-means[j])/vars[j])-1)
    estimates <- c(estimates, jth_estimate)
  }
  return(estimates)
}


MME2 <- function(data){ #Compute the MME for Dirichlet parameters 
  means <- smean(data)
  vars <- svar(data)
  estimates <- c()
  d <- length(data[1,])
  for(j in 1:d){
    jth_estimate <- means[j]*(prod((means[-j]*(1-means[-j])/vars[-j])-1)^(1/(d-1)))
    estimates <- c(estimates, jth_estimate)
  }
  return(estimates)
}

bias = function(estimate, truth){
  mean(estimate) - truth
}



mse = function(estimate, truth){
  mean((estimate - truth) ^ 2)
}

msem = function(estimate, truth){
  mean(crossprod(estimate-truth, estimate-truth))
}


error = function(estimate, truth){
  estimate - truth
}


iterr <- function(estimate, truth){
  for(i in 1:length(estimate)){
    
  }
}


aerror = function(estimate, truth){
  abs(estimate - truth)
}


dirFIMPO <- function(alpha){
  FIMPO <- matrix(nrow=length(alpha), ncol=length(alpha), -trigamma(sum(alpha)))
  diagonal <- c()
  for(i in 1:length(alpha)){
    diagonal <- c(diagonal, trigamma(alpha[i])-trigamma(sum(alpha)))
  }
  diag(FIMPO) <- diagonal
  return(FIMPO)
}

cross<-function(err){
  
  res <- array(dim=c(length(err[1,]), length(err[1,]), length(err[,1])))
  for(i in 1:length(err[,1])){
    res[,,i] <- err[i,]%*%t(err[i,]) #iteration doesn't quite work
  }
  #return(res)
  return(rowMeans( res , dims = 2 ))
}


sirt_digamma1 <- function(x, h=1e-3) #Hidden utility function. I couldn't access it through R 
  #but I found it in the package on Github. 
  #It's an implementation of the trigamma function (via numerical derivative of digamma)
{
    ( digamma(x+h) - digamma(x-h) ) / (2*h)
}


dirichlet.mle <- function (x, weights = NULL, eps = 10^(-5), convcrit = 1e-05, 
    maxit = 1000, oldfac = 0.3, progress = FALSE) #The mle estimations function
{
    N <- nrow(x)
    K <- ncol(x)
    x <- (x + eps)/(1 + 2 * eps)
    x <- x/rowSums(x)
    N <- nrow(x)
    if (is.null(weights)) {
        weights <- rep(1, N)
    }
    weights <- N * weights/sum(weights)
    log.pbar <- colMeans(weights * log(x))
    alphaprob <- colMeans(x * weights)
    p2 <- mean(x[, 1]^2 * weights)
    xsi <- (alphaprob[1] - p2)/(p2 - (alphaprob[1])^2)
    alpha <- xsi * alphaprob
    K1 <- matrix(1, K, K)
    conv <- 1
    iter <- 1
    while ((conv > convcrit) & (iter < maxit)) {    #This is the stepwise iteration that converges at the global max     
        alpha0 <- alpha
        g <- N * digamma(sum(alpha)) - N * digamma(alpha) + N * 
            log.pbar
        z <- N * sirt_digamma1(sum(alpha))
        H <- diag(-N * sirt_digamma1(alpha)) + z
        alpha <- alpha0 - solve(H, g)
        alpha[alpha < 0] <- 1e-10
        alpha <- alpha0 + oldfac * (alpha - alpha0)
        conv <- max(abs(alpha0 - alpha))
        if (progress) {
            print(paste(iter, sum(alpha), conv))
            utils::flush.console()
        }
        iter <- iter + 1
    }
    alpha0 <- sum(alpha)
    xsi <- alpha/alpha0
    res <- list(alpha = alpha, alpha0 = alpha0, xsi = xsi)
    return(res)
}


MLE <- dirichlet.mle



dirtest <- function(K, N, d, delta){
  mmes <- matrix(nrow=1, ncol=d, rep(0,d))
  mmes2 <- matrix(nrow=1, ncol=d, rep(0,d))
  mles <- matrix(nrow=1, ncol=d, rep(0,d))
#  alphas <- matrix(nrow=1, ncol=P, rep(0,P))

    for(k in 1:K){
    alpha <- delta #Use for symmetrix Dirichlets
#    alpha <- c(1/2, 50)
     dirdata <- matrix(alpha, nrow=N, ncol=length(alpha), byrow=TRUE) %>%  #data matrix initialization
      sirt::dirichlet.simul() #data matrix simulation
    
    mmes <- rbind(mmes, MME(dirdata))
    mmes2 <- rbind(mmes2, MME2(dirdata))
    mles <- rbind(mles, MLE(dirdata)$alpha)
 #   alphas <- rbind(alphas, alpha)
    }
 # rownames(alphas) <- NULL
  return(list(mme = mmes[-1,], mme2 = mmes2, mle = mles[-1,]))
}


#Making the final results


```



```{r}
K=10000
N=100
d=2
delta=200

start<- Sys.time()
t100 <- dirtest(K=K,N=N,d=d, delta=delta)
Sys.time() - start

K=10000
N=50


start<- Sys.time()
t50 <- dirtest(K=K,N=N,d=d, delta=delta)
Sys.time() - start


K=10000
N=20


start<- Sys.time()
t20 <- dirtest(K=K,N=N,d=d, delta=delta)
Sys.time() - start

K=10000
N=10


start<- Sys.time()
t10 <- dirtest(K=K,N=N,d=d, delta=delta)
Sys.time() - start

K=10000
N=5


start<- Sys.time()
t5 <- dirtest(K=K,N=N,d=d, delta=delta)
Sys.time() - start

```
```{r}
tr <- list(t5, t10, t20, t50, t100)
```

symm error
```{r}
t<-t100

err <- error(t$mme, delta)
aerr <- aerror(t$mme, delta)
b1<-(apply(err, 2, mean))
a1<-(apply(aerr, 2, mean))
s1<-(apply(t$mme, 2, sd))

tmme2 <- na.omit(t$mme2)
err <- error(tmme2, delta)
aerr <- aerror(t$mme2, delta)
b2<-(apply(err, 2, mean))
a2<-(apply(aerr, 2, mean))
s2<-(apply(t$mme2, 2, sd))


err <- error(t$mle, delta)
aerr <- aerror(t$mle, delta)
b3<-(apply(err, 2, mean))
a3<-(apply(aerr, 2, mean))
s3<-(apply(t$mle, 2, sd))


res<-data.frame(b1, b2, b3, s1, s2, s3, a1, a2, a3)
round(res, 3)
bias<- data.frame(b1, b2, b3)
aerr<- data.frame(a1, a2, a3) %>% rename(b1=a1, b2=a2, b3=a3)
se<- data.frame(s1, s2, s3) %>% rename(b1=s1, b2=s2, b3=s3)

round(rbind(bias, se, aerr),3)
```
```{r}
t<-t50
```

n=50, delta=1/2
```{r}
hist(t$mme[,1])
hist(t$mme[,2])
hist(t$mme2[,1])
hist(t$mme2[,2])
hist(t$mle[,1])
hist(t$mle[,2])
```


```{r}
t<-tr[[5]]
```


```{r}
t<-t100
err <- error(t$mme, delta)
data.frame(round(cross(err),3))


err <- error(t$mme2, delta)
data.frame(round(cross(err),3))

err <- error(t$mle, delta)
data.frame(round(cross(err),3))
```

asymmgen
```{r}
K=10000
N=100
d=2
delta=100

start<- Sys.time()
t100 <- dirtest(K=K,N=N,d=d, delta=delta)
Sys.time() - start

K=10000
N=50


start<- Sys.time()
t50 <- dirtest(K=K,N=N,d=d, delta=delta)
Sys.time() - start


K=10000
N=20


start<- Sys.time()
t20 <- dirtest(K=K,N=N,d=d, delta=delta)
Sys.time() - start

K=10000
N=10


start<- Sys.time()
t10 <- dirtest(K=K,N=N,d=d, delta=delta)
Sys.time() - start

K=10000
N=5


start<- Sys.time()
t5 <- dirtest(K=K,N=N,d=d, delta=delta)
Sys.time() - start

```


<!-- symm error -->
```{r}
t<-t100

err <- error(t$mme[,1], 5)
err2 <- error(t$mme[,2], delta)
aerr <- aerror(t$mme[,1], 5)
aerr2 <- aerror(t$mme[,2], delta)
b1<-c(mean(err), mean(err2))
a1<-c(mean(aerr), mean(aerr2))
s1<-c(sd(t$mme[,1]), sd(t$mme[,2]))

tmme2 <- na.omit(t$mme2)
err <- error(t$mme2[,1], 5)
err2 <- error(t$mme2[,2], delta)
aerr <- aerror(t$mme2[,1], 5)
aerr2 <- aerror(t$mme2[,2], delta)
b2<-c(mean(err), mean(err2))
a2<-c(mean(aerr), mean(aerr2))
s2<-c(sd(t$mme2[,1]), sd(t$mme2[,2]))


err <- error(t$mle[,1], 5)
err2 <- error(t$mle[,2], delta)
aerr <- aerror(t$mle[,1], 5)
aerr2 <- aerror(t$mle[,2], delta)
b3<-c(mean(err), mean(err2))
a3<-c(mean(aerr), mean(aerr2))
s3<-c(sd(t$mle[,1]), sd(t$mle[,2]))


res<-data.frame(b1, b2, b3, s1, s2, s3, a1, a2, a3)
round(res, 3)
bias<- data.frame(b1, b2, b3)
aerr<- data.frame(a1, a2, a3) %>% rename(b1=a1, b2=a2, b3=a3)
se<- data.frame(s1, s2, s3) %>% rename(b1=s1, b2=s2, b3=s3)

round(rbind(bias, se, aerr),3)
```


```{r}
bias1 <- c(4.574, 1.205, 0.488, 0.173, 0.084)
bias2 <- c(4.574, 1.205, 0.488, 0.173, 0.084)
bias3 <- c(7.311, 2.063, 0.859, 0.310, 0.151)

err1 <- c(22.581,3.895,2.002,1.085,0.726)
err2 <- c(22.581,3.895,2.002,1.086,0.726)
err3 <- c(28.228,4.331,2.103,1.1,0.727)

n<-c(5, 10, 20, 50, 100,5, 10, 20, 50, 100,5, 10, 20, 50, 100)


biases<- c(bias1, bias2, bias3)
errs <- c(err1, err2, err3)
est = c(rep("MME1", 5),rep("MME2", 5),rep("MLE", 5))


dat<- data.frame(biases, errs, est,n)
```




```{r}
theme_set(theme_bw())
library(ggplot2)
# Default bar plot
p<- ggplot(dat, aes(x=n, y=biases, color=est)) + 
  geom_point(position=position_dodge(width=4)) +
  geom_errorbar(aes(ymin=biases-errs, ymax=biases+errs), width=.2,
                 position=position_dodge(4))
p
```


```{r}
sink
```

simtest
```{r}
estim <- function()



```


```{r}



t<-t100

err <- error(t$mme[,1], 5)
err2 <- error(t$mme[,2], delta)
aerr <- aerror(t$mme[,1], 5)
aerr2 <- aerror(t$mme[,2], delta)
b1<-c(mean(err), mean(err2))
a1<-c(mean(aerr), mean(aerr2))
s1<-c(sd(t$mme[,1]), sd(t$mme[,2]))

tmme2 <- na.omit(t$mme2)
err <- error(t$mme2[,1], 5)
err2 <- error(t$mme2[,2], delta)
aerr <- aerror(t$mme2[,1], 5)
aerr2 <- aerror(t$mme2[,2], delta)
b2<-c(mean(err), mean(err2))
a2<-c(mean(aerr), mean(aerr2))
s2<-c(sd(t$mme2[,1]), sd(t$mme2[,2]))


err <- error(t$mle[,1], 5)
err2 <- error(t$mle[,2], delta)
aerr <- aerror(t$mle[,1], 5)
aerr2 <- aerror(t$mle[,2], delta)
b3<-c(mean(err), mean(err2))
a3<-c(mean(aerr), mean(aerr2))
s3<-c(sd(t$mle[,1]), sd(t$mle[,2]))


res<-data.frame(b1, b2, b3, s1, s2, s3, a1, a2, a3)
#round(res, 3)
bias<- data.frame(b1, b2, b3)
aerr<- data.frame(a1, a2, a3) %>% rename(b1=a1, b2=a2, b3=a3)
se<- data.frame(s1, s2, s3) %>% rename(b1=s1, b2=s2, b3=s3)



sink("res.txt")
print(round(rbind(bias, se, aerr),3))
sink()



```
```{r}
unlink("res.csv")
```








```{r}
itmean <- function(x){
  y<-c()
  y <- c(y, x[1])
  for(i in 2:length(x)){
      
    yn <- (i/(i+1))*y[i-1]+(1/(i+1))*x[i]
    y <- c(y, yn)
  }
 y[length(x)]
}
```

```{r}
itvar <- function(x){
  y<-c()
  y <- c(y, x[1])
  for(i in 2:length(x)){
      
    yn <- ((i-1)/i)*y[i-1]+(1/(i+1))*(x[i-1]-x[i])^2
    y <- c(y, yn)
  }
 y[length(x)]
}
```

```{r}
itsd <- function(x){
  y<-c()
  y <- c(y, x[1])
  for(i in 2:length(x)){
      
    yn <- ((i-1)/i)*y[i-1]+(1/(i+1))*(x[i-1]-x[i])^2
    y <- c(y, yn)
  }
 sqrt(y[length(x)])
}
```



```{r}
itmean(err)

  y<-c()
  y <- c(y, err[1])
  for(i in 2:length(err)){
      
    yn <- (i/(i+1))*y[i-1]+(1/(i+1))*err[i]
    y <- c(y, yn)
  }
y[10000]
mean(err)
itmean(err)
y
```
```{r}
bias
```

```{r}
sqrt(itvar(err))
itsd(err)
sd(err)
```


```{r}
plot(y)

```



